#+STARTUP: latexpreview

* 1° de Bachillerato (16 años)

Del libro [[http://www.apuntesmareaverde.org.es/grupos/mat/LOMLOE/Bachillerato/Matematicas_I.pdf][Matemáticas I (1º de Bachillerato)]] de Apuntes marea Verde.

** Números reales y complejos

*** Valor absoluto

+ 10 No negatividad: $|a| \geq 0$.

+ 10
  #+begin_teorema
  Simetría: $|a| = |-a|$.
  #+end_teorema
  #+begin_demostracion
  Si $a > 0$, entonces
  \begin{align*}
  |a| &= a \\
      &= -(-a) \\
      &= |-a|
  \end{align*}

  Si $a = 0$, entonces
  \begin{align*}
      |a| &= |0| \\
          &= |-0| \\
          &= |-a|
  \end{align*}

  Si $a < 0$, entonces
  \begin{align*}
  |a| &= -a \\
      &= |-a|
  \end{align*}
  #+end_demostracion

+ 10 Definición positiva: Si $|a| = 0$, entonces $a = 0$.

+ 10 Valor absoluto y producto: $|a \times b| = |a| \times |b|$.

+ 10 Desigualdad triangular: $|a + b| \leq |a| + |b|$.

*** Distancia en la recta real

+ 12 La distancia está definida por $\mbox{dist}(x,y) = |x - y|$ y
  verifica las siguientes propiedades:
  + $\mbox{dist}(x,y) = 0$ syss $x = y$
  + $\mbox{dist}(x,y) = \mbox{dist}(y,x)$
  + $\mbox{dist}(x,y) \leq \mbox{dist}(x,z) + \mbox{dist}(z,y)$

*** Números complejos

+ 21 Operaciones en forma binómica:
  + $(x + iy) + (u + iv) = (x + u) + i(y + v)$.
  + $(x + iy) (u + iv) = (xu - yv) + i(xv + yu)$.

+ 27 Propiedades del módulo, del conjugado y del argumento de un número
  complejo:
  + $\overline{z+w} = \overline{z} + \overline{w}$
  + $\overline{z-w} = \overline{z} - \overline{w}$
  + $\overline{z \cdot w} = \overline{z} \cdot \overline{w}$.
  + $\arg({\overline{z}}) = -\arg({z})$.
  + $z \in \mathbb{R} \iff z = \overline{z}$.
  + $z \cdot \overline{z} = |z|^{2}$
  + $|\overline{z}| = |z|$.
  + $|z \cdot w| = |z| \cdot |w|$
  + $\left|\dfrac{z}{w}\right| = \dfrac{|z|}{|w|}$
  + $|z| = 0 \iff z = 0$
  + $\Re(z) = \dfrac{z + \overline{z}}{2}$
  + $\Im(z) = \dfrac{z - \overline{z}}{2i}$
  + $\Re(z) \leq |z|$
  + $\Im(z) \leq |z|$
  + $|z| \leq \Re(z) + \Im(z)$
  + $||z| - |w|| \leq |z + w| \leq |z| + |w|$

*** Operaciones entre números complejos en forma trigonométrica

+ 29
  #+begin_teorema
  Para multiplicar números complejos expresados en forma polar o en
  trigonométrica basta multiplicar sus módulos y sumar sus argumento
  #+end_teorema
  #+begin_demostracion
\begin{align*}
z_{} \cdot z' &= r_{}(\cos \alpha + i\sen \alpha) \cdot r'(\cos \beta + i \sen \beta)  \\
       &= (r \cdot r') ((\cos \alpha \cos \beta - \sen \alpha \sen \beta) + i (\sen \alpha \cos \beta - \cos \alpha \sen \beta))   \\
       &= (r \cdot r') (\cos (\alpha + \beta) + i \sen (\alpha + \beta))  \\
\end{align*}
  #+end_demostracion

+ Para dividir números complejos, basta dividir sus módulos y restar
  sus argumentos.

+ El inverso de un número complejo distinto de cero tiene como módulo,
  el inverso del módulo, y como argumento, el opuesto del argumento.

+ Para elevar un número complejo a una potencia, se eleva el módulo a
  dicha potencia, y se multiplica el argumento por el exponente.

** Trigonometría

*** Razones trigonométricas de la suma de ángulos

+ 116 $\sen(a + b) = \sen(a)\cos(b) + \cos(a)\sen(b)$

+ 116 $\cos(a + b) = \cos(a)\cos(b) - \sen(a)\sen(b)$

+ 117
  #+begin_teorema
  $\tan(a+b) = \dfrac{\tan(a)+\tan(b)}{1-\tan(a)\tan(b)}$
  #+end_teorema
  #+begin_demostracion
  \begin{align*}
  \tan(a+b) &= \dfrac{\sen(a+b)}{\cos(a+b)} \\
            &= \dfrac{\sen(a)\cos(b)+\cos(a)\sen(b)}
                     {\cos(a)\cos(b)-\sen(a)\sen(b)} \\
            &= \dfrac{\dfrac{\sen(a)\cos(b)+\cos(a)\sen(b)}{\cos(a)\cos(b)}}
                     {\dfrac{\cos(a)\cos(b)-\sen(a)\sen(b)}{\cos(a)\cos(b)}} \\
            &= \dfrac{\tan(a)+\tan(b)}{1-\tan(a)\tan(b)} \\
  \end{align*}
  #+end_demostracion

*** Razones trigonométricas de la resta de ángulos

+ 117 $\sen(-a) = -\sen(a)$

+ 117 $\cos(-a) = \cos(a)$

+ 117 $\tan(-a) = -\tan(a)$

+ 118 $\sen(a-b) = \sen(a)\cos(b) - \cos(a)\sen(b)$

+ 118 $\cos(a-b) = \cos(a)\cos(b) + \sen(a)\sen(b)$

+ 118 $\tan(a-b) = \dfrac{\tan(a) - \tan(b)}{1 + \tan(a)\tan(b)}$

*** Razones trigonométricas del ángulo doble

+ 118 $\sen(2a) = 2\sen(a)\cos(a)$

+ 118 $\cos(2a) = \cos^{2}(a) - \sen^2(a)$

+ 118 $\tan(2a) = \dfrac{2\tan(a)}{1 - \tan^{2}(a)}$

+ 119 $\sen\left(\dfrac{a}{2}\right) = \pm\sqrt{\dfrac{1-\cos(a)}{2}}$


+ 119 $\cos\left(\dfrac{a}{2}\right) = \pm\sqrt{\dfrac{1+\cos(a)}{2}}$


+ 119 $\tan\left(\dfrac{a}{2}\right) = \pm\sqrt{\dfrac{1-\cos(a)}{1+\cos(a)}}$

*** Transformaciones de sumas de razones trigonométricas en productos

+ Fórmula de Simpson de seno por coseno: \\
  #+begin_teorema
  $\sen \alpha \cos \beta = \dfrac{\sen(\alpha+\beta) + \sen(\alpha-\beta)}{2}$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Simpson%27s_Formulas/Sine_by_Cosine][Simpson's formulas/Sine by cosine]])

  \begin{align*}
   &  \dfrac{\sen(\alpha+\beta) + \sen(\alpha-\beta)}{2} \\
   &= \dfrac{(\sen \alpha \cos \beta + \cos \alpha \sen \beta) + (\sen \alpha \cos \beta - \cos \alpha \sen \beta)}{2} \\
   &= \dfrac{2 \sen \alpha \cos \beta}{2} \\
   &= \sen \alpha \cos \beta
  \end{align*}
  #+end_demostracion

+ 120
  #+begin_teorema
  $\sen(a) + \sen(b) =
  2\sen\left(\dfrac{a+b}{2}\right)\cos\left(\dfrac{a-b}{2}\right)$
  #+end_teorema
  #+begin_demostracion
  (En ProofWiki [[https://proofwiki.org/wiki/Prosthaphaeresis_Formulas/Sine_plus_Sine][Prosthaphaeresis formulas/Sine plus sine]]).

  \begin{align*}
    &  2 \sen\left(\dfrac{\alpha+\beta}{2}\right)
         \cos\left(\dfrac{\alpha-\beta}{2}\right) \\
    &= 2 \dfrac{\sen\left(\dfrac{\alpha+\beta}{2} + \dfrac{\alpha-\beta}{2}\right) +
                \sen\left(\dfrac{\alpha+\beta}{2} - \dfrac{\alpha-\beta}{2}\right)}
               {2}
         & \mbox{Fórmula de Simpson} \\
    &= \sen \frac{2\alpha}{2} + \sen \frac{2\beta}{2} \\
    &= \sen \alpha + \sen \beta \\
  \end{align*}
  #+end_demostracion

+ 120
  #+begin_teorema
  $\sen(a) - \sen(b) =
  2\cos\left(\dfrac{a+b}{2}\right)\sen\left(\dfrac{a-b}{2}\right)$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Prosthaphaeresis_Formulas/Sine_minus_Sine][Prosthaphaeresis formulas/sine minus sine]])

  \begin{align*}
    &  2 \cos\left(\dfrac{\alpha+\beta}{2}\right)
         \sen\left(\dfrac{\alpha-\beta}{2}\right) \\
    &= 2 \dfrac{\sen\left(\dfrac{\alpha-\beta}{2} + \dfrac{\alpha+\beta}{2}\right) +
                \sen\left(\dfrac{\alpha-\beta}{2} - \dfrac{\alpha+\beta}{2}\right)}
               {2}
         & \mbox{Fórmula de Simpson} \\
    &= \sen \frac{2\alpha}{2} - \sen \frac{2\beta}{2} \\
    &= \sen \alpha - \sen \beta \\
  \end{align*}
  #+end_demostracion

+ Fórmula de Simpson de coseno por coseno: \\
  #+begin_teorema
  $\cos \alpha \cos \beta = \dfrac{\cos(\alpha-\beta) + \cos(\alpha+\beta)}{2}$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Simpson%27s_Formulas/Cosine_by_Cosine][Simpson's Formulas/Cosine by Cosine]])

  \begin{align*}
   &  \dfrac{\cos(\alpha-\beta) + \sen(\alpha+\beta)}{2} \\
   &= \dfrac{(\cos \alpha \cos \beta + \sen \alpha \sen \beta) + (\cos \alpha \cos \beta - \sen \alpha \sen \beta)}{2} \\
   &= \dfrac{2 \cos \alpha \cos \beta}{2} \\
   &= \cos \alpha \cos \beta
  \end{align*}
  #+end_demostracion

+ 120
  #+begin_teorema
  $\cos a  + \cos b  =
  2\cos\left(\dfrac{a+b}{2}\right)\cos\left(\dfrac{a-b}{2}\right)$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Prosthaphaeresis_Formulas/Cosine_plus_Cosine][Prosthaphaeresis Formulas/Cosine plus Cosine]]).

  \begin{align*}
    &  2 \cos\left(\dfrac{\alpha+\beta}{2}\right)
         \cos\left(\dfrac{\alpha-\beta}{2}\right) \\
    &= 2 \dfrac{\cos\left(\dfrac{\alpha-\beta}{2} - \dfrac{\alpha-\beta}{2}\right) +
                \cos\left(\dfrac{\alpha+\beta}{2} + \dfrac{\alpha-\beta}{2}\right)}
               {2}
         & \mbox{Fórmula de Simpson} \\
    &= \cos \frac{2\beta}{2} + \cos \frac{2\alpha}{2} \\
    &= \cos \alpha + \cos \beta \\
  \end{align*}
  #+end_demostracion

  + 120
  #+begin_teorema
  $\cos a  - \cos b  =
  -2\sen\left(\dfrac{a+b}{2}\right)\sen\left(\dfrac{a-b}{2}\right)$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Prosthaphaeresis_Formulas/Cosine_minus_Cosine][Prosthaphaeresis Formulas/Cosine minus Cosine]]).

  \begin{align*}
    &  -2 \sen\left(\dfrac{\alpha+\beta}{2}\right)
          \sen\left(\dfrac{\alpha-\beta}{2}\right) \\
    &= -2 \dfrac{\cos\left(\dfrac{\alpha+\beta}{2} - \dfrac{\alpha-\beta}{2}\right) -
                 \cos\left(\dfrac{\alpha+\beta}{2} + \dfrac{\alpha-\beta}{2}\right)}
               {2}
         & \mbox{Fórmula de Simpson} \\
    &= -\left(\cos \frac{2\beta}{2} - \cos \frac{2\alpha}{2}\right) \\
    &= \cos \alpha - \cos \beta \\
  \end{align*}
  #+end_demostracion

*** Resolución general de triángulos

+ 129
  #+begin_teorema
  Teorema del coseno: Sea $\triangle ABC$ un triángulos cuyos lados
  $a, b, c$ son tales que $a$ es opuesto de $A$, $b$ es opuestos de $B$
  y $c$ es opuesto de $C$. Entonces,
  $$c^2 = a^2 + b^2 - 2 a b \cos C$$
  #+end_teorema
  #+begin_demostracion
  (En ProofWiki [[https://proofwiki.org/wiki/Law_of_Cosines][Law of cosines]]).

  /Caso de triángulo rectángulo/

  Sea $\triangle ABC$ un triángulo rectángulo tal que $\angle A$ recto.

  file:./fig/teorema-coseno-1.png

  \begin{align*}
  a^2 &= b^2 + c^2
      && \text{Teorema de Pitágoras} \\
  c^2 &= a^2 - b^2
      && \text{Despejando $c^{2}$}\\
      &= a^2 - 2 b^2 + b^2
      && \text{Sumando $0 = b^2 - b^2$ a la derecha} \\
      &= a^2 - 2 a b \left({\frac b a}\right) + b^2
      && \text{Multiplicando $2 b^2$ por $\dfrac a a$} \\
      &= a^2 + b^2 - 2 a b \cos C
      && \text{Por la definición de $\cos C = \dfrac b a$}
  \end{align*}


  /Caso del triángulo acutángulo/

  Sea $\triangle ABC$ un triángulo acutángulo.

  file:./fig/teorema-coseno.2.png

  Sea $BD$ perpendicular a $AC$ y se definen $h = BD$, $e = CD$ y $f = AD$.

  Los triángulos $\triangle CDB$ y $\triangle ADB$ son rectángulos. Por tanto, \\
\begin{align*}
c^2 &= h^2 + f^2
    && \text{Teorema de Pitágoras} \\
    &= a^2 - e^2 + f^2
    && \text{Teorema de Pitágoras} \\
    &= a^2 - e^2 + f^2 + 2e^2 - 2e^2 + 2ef - 2ef
    && \text{Sumando $2e^2 - 2e^2 + 2ef - 2ef$} \\
    &= a^2 + (e^2 + f^2 + 2ef) - 2e(e + f)
    && \text{Agrupando} \\
    &= a^2 + (e + f)^2 - 2e(e+f)
    && \text{Cuadrado del binomio} \\
    &= a^2 + b^2 - 2eb
    && \text{Sustituyendo $b = e + f$} \\
    &= a^2 + b^2 - 2 a b \cos C
    && \text{Definición de $\cos C = \frac{e}{a}$} \\
\end{align*}

  /Caso del triángulo obtusángulo/

  Sea $\triangle ABC$ un triángulo obtusángulo.

  file:./fig/teorema-coseno-3.png

  Se extiende $AC$ y sea $BD$ perpendicular a $AC$. Se define $h = BD$, $e = CD$ y $f = AD$.

  Entonces $\triangle CDB$ y $\triangle ADB$ son triángulos rectángulos. Por tanto,

  \begin{align*}
c^2 &= h^2 + f^2
    && \text{Teorema de Pitágoras} \\
    &= a^2 - e^2 + f^2
    && \text{Teorema de Pitágoras} \\
    &= a^2 - (b + f)^2 + f^2
    && \text{Por definición de $e$ y $f$} \\
    &= a^2 - b^2 - f^2 - 2bf + f^2
    && \text{Expandiendo el cuadrado del binomio} \\
    &= a^2 - b^2 - 2bf
    && \text{Cancelando $f^2 - f^2$} \\
    &= a^2 - b^2 - 2bf + 2b^2 - 2b^2
    && \text{Sumando y restando $2b^2$} \\
    &= a^2 + b^2 - 2b(b + f)
    && \text{Reagrupando} \\
    &= a^2 + b^2 - 2be \\
    &= a^2 + b^2 - 2 a b \cos C
    && \text{Por definición de $\cos C = \frac{e}{a}$}
  \end{align*}
    #+end_demostracion

+ 129
  #+begin_teorema
  Teorema de Pitágoras: Sea $\triangle ABC$ un triángulo rectángulo
  $c$ como su hipotenusa. Entonces,
  $$a^2 + b^2 = c^2$$
  #+end_teorema
  #+begin_demostracion
  \begin{align*}
  c^2 &= a^2 + b^2 - 2 a b \cos\left(\frac{\pi}{2}\right) \\
      &= a^2 + b^2
  \end{align*}
  #+end_demostracion

+ 131.
  #+begin_teorema
  Teorema del seno: para cualquier triángulo $\triangle ABC$:

$$\dfrac a {\sen(\alpha)} = \dfrac b {\sen(\beta)} = \dfrac c {\sen(\gamma)}$$

donde $a$, $b$, and $c$ son los lados opuestoa a los vértices $\alpha$, $\beta$ y $\gamma$, respectivamente.
  #+end_teorema
  #+begin_demostracion
  (En ProofWiki [[https://proofwiki.org/wiki/Law_of_Sines][Law of sines]]).

  /Caso del triángulo acutángulo/

  file:./fig/teorema-seno.png

  Por definición del seno, se tiene $\sen(\alpha) = \frac{h}{b}$ y
  $\sen(\beta) = \frac{h}{a}$.

  Despejando $h$, se tiene $h = b \sen(\alpha)$ y $h = a \sen(\beta)$.

  Igualando, se tiene $b \sen(\alpha) = a \sen(\beta)$.

  Por tanto. $\dfrac a {\sen(\alpha)} = \dfrac b {\sen(\beta)}$


  Los casos de los triángulos obtusángulo y rectángulo se deja como ejercicio.
  #+end_demostracion

+ 132.
  #+begin_teorema
  Si un triángulo es obtusángulo, el ángulo obtuso es opuesto al lado más grande.
  #+end_teorema
  #+begin_demostracion
  Supongamos un triángulo obtusángulo de lados $a$, $b$ y $c$ con
  $\alpha$ el ángulo opuesto a $a$ obtuso. Debemos ver $a > b$ y $a > c$.

  Por el teorema del coseno $a^2 = b^2 + c^2 - 2ab \cos(\alpha)$. Como
  el ángulo $\alpha$ es obtuso entonces $\cos(\alpha) < 0$
  y $2ab \cos(\alpha) < 0$. Eso significa que $c^2 - 2ab \cos(\alpha) >
  0$
  y, por tanto, $a^2 > b^2$. Como los dos son positivos,
  tomando raíces se deduce $a > b$.

  Del mismo modo se demuestra que $a > c$.
  #+end_demostracion
