#+STARTUP: latexpreview

* 1° de Bachillerato (16 años)

Del libro [[http://www.apuntesmareaverde.org.es/grupos/mat/LOMLOE/Bachillerato/Matematicas_I.pdf][Matemáticas I (1º de Bachillerato)]] de Apuntes marea Verde.

** Números reales y complejos

*** Valor absoluto

+ 10 No negatividad: $|a| \geq 0$.

+ 10
  #+begin_teorema
  Simetría: $|a| = |-a|$.
  #+end_teorema
  #+begin_demostracion
  Si $a > 0$, entonces
  \begin{align*}
  |a| &= a \\
      &= -(-a) \\
      &= |-a|
  \end{align*}

  Si $a = 0$, entonces
  \begin{align*}
      |a| &= |0| \\
          &= |-0| \\
          &= |-a|
  \end{align*}

  Si $a < 0$, entonces
  \begin{align*}
  |a| &= -a \\
      &= |-a|
  \end{align*}
  #+end_demostracion

+ 10 Definición positiva: Si $|a| = 0$, entonces $a = 0$.

+ 10 Valor absoluto y producto: $|a \times b| = |a| \times |b|$.

+ 10 Desigualdad triangular: $|a + b| \leq |a| + |b|$.

*** Distancia en la recta real

+ 12 La distancia está definida por $\mbox{dist}(x,y) = |x - y|$ y
  verifica las siguientes propiedades:
  + $\mbox{dist}(x,y) = 0$ syss $x = y$
  + $\mbox{dist}(x,y) = \mbox{dist}(y,x)$
  + $\mbox{dist}(x,y) \leq \mbox{dist}(x,z) + \mbox{dist}(z,y)$

*** Números complejos

+ 21 Operaciones en forma binómica:
  + $(x + iy) + (u + iv) = (x + u) + i(y + v)$.
  + $(x + iy) (u + iv) = (xu - yv) + i(xv + yu)$.

+ 27 Propiedades del módulo, del conjugado y del argumento de un número
  complejo:
  + $\overline{z+w} = \overline{z} + \overline{w}$
  + $\overline{z-w} = \overline{z} - \overline{w}$
  + $\overline{z \cdot w} = \overline{z} \cdot \overline{w}$.
  + $\arg({\overline{z}}) = -\arg({z})$.
  + $z \in \mathbb{R} \iff z = \overline{z}$.
  + $z \cdot \overline{z} = |z|^{2}$
  + $|\overline{z}| = |z|$.
  + $|z \cdot w| = |z| \cdot |w|$
  + $\left|\dfrac{z}{w}\right| = \dfrac{|z|}{|w|}$
  + $|z| = 0 \iff z = 0$
  + $\Re(z) = \dfrac{z + \overline{z}}{2}$
  + $\Im(z) = \dfrac{z - \overline{z}}{2i}$
  + $\Re(z) \leq |z|$
  + $\Im(z) \leq |z|$
  + $|z| \leq \Re(z) + \Im(z)$
  + $||z| - |w|| \leq |z + w| \leq |z| + |w|$

*** Operaciones entre números complejos en forma trigonométrica

+ 29
  #+begin_teorema
  Para multiplicar números complejos expresados en forma polar o en
  trigonométrica basta multiplicar sus módulos y sumar sus argumento
  #+end_teorema
  #+begin_demostracion
\begin{align*}
z_{} \cdot z' &= r_{}(\cos \alpha + i\sen \alpha) \cdot r'(\cos \beta + i \sen \beta)  \\
       &= (r \cdot r') ((\cos \alpha \cos \beta - \sen \alpha \sen \beta) + i (\sen \alpha \cos \beta - \cos \alpha \sen \beta))   \\
       &= (r \cdot r') (\cos (\alpha + \beta) + i \sen (\alpha + \beta))  \\
\end{align*}
  #+end_demostracion

+ Para dividir números complejos, basta dividir sus módulos y restar
  sus argumentos.

+ El inverso de un número complejo distinto de cero tiene como módulo,
  el inverso del módulo, y como argumento, el opuesto del argumento.

+ Para elevar un número complejo a una potencia, se eleva el módulo a
  dicha potencia, y se multiplica el argumento por el exponente.

** Trigonometría

*** Razones trigonométricas de la suma de ángulos

+ 116 $\sen(a + b) = \sen(a)\cos(b) + \cos(a)\sen(b)$

+ 116 $\cos(a + b) = \cos(a)\cos(b) - \sen(a)\sen(b)$

+ 117
  #+begin_teorema
  $\tan(a+b) = \dfrac{\tan(a)+\tan(b)}{1-\tan(a)\tan(b)}$
  #+end_teorema
  #+begin_demostracion
  \begin{align*}
  \tan(a+b) &= \dfrac{\sen(a+b)}{\cos(a+b)} \\
            &= \dfrac{\sen(a)\cos(b)+\cos(a)\sen(b)}
                     {\cos(a)\cos(b)-\sen(a)\sen(b)} \\
            &= \dfrac{\dfrac{\sen(a)\cos(b)+\cos(a)\sen(b)}{\cos(a)\cos(b)}}
                     {\dfrac{\cos(a)\cos(b)-\sen(a)\sen(b)}{\cos(a)\cos(b)}} \\
            &= \dfrac{\tan(a)+\tan(b)}{1-\tan(a)\tan(b)} \\
  \end{align*}
  #+end_demostracion

*** Razones trigonométricas de la resta de ángulos

+ 117 $\sen(-a) = -\sen(a)$

+ 117 $\cos(-a) = \cos(a)$

+ 117 $\tan(-a) = -\tan(a)$

+ 118 $\sen(a-b) = \sen(a)\cos(b) - \cos(a)\sen(b)$

+ 118 $\cos(a-b) = \cos(a)\cos(b) + \sen(a)\sen(b)$

+ 118 $\tan(a-b) = \dfrac{\tan(a) - \tan(b)}{1 + \tan(a)\tan(b)}$

*** Razones trigonométricas del ángulo doble

+ 118 $\sen(2a) = 2\sen(a)\cos(a)$

+ 118 $\cos(2a) = \cos^{2}(a) - \sen^2(a)$

+ 118 $\tan(2a) = \dfrac{2\tan(a)}{1 - \tan^{2}(a)}$

+ 119 $\sen\left(\dfrac{a}{2}\right) = \pm\sqrt{\dfrac{1-\cos(a)}{2}}$


+ 119 $\cos\left(\dfrac{a}{2}\right) = \pm\sqrt{\dfrac{1+\cos(a)}{2}}$


+ 119 $\tan\left(\dfrac{a}{2}\right) = \pm\sqrt{\dfrac{1-\cos(a)}{1+\cos(a)}}$

*** Transformaciones de sumas de razones trigonométricas en productos

+ Fórmula de Simpson de seno por coseno: \\
  #+begin_teorema
  $\sen \alpha \cos \beta = \dfrac{\sen(\alpha+\beta) + \sen(\alpha-\beta)}{2}$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Simpson%27s_Formulas/Sine_by_Cosine][Simpson's formulas/Sine by cosine]])

  \begin{align*}
   &  \dfrac{\sen(\alpha+\beta) + \sen(\alpha-\beta)}{2} \\
   &= \dfrac{(\sen \alpha \cos \beta + \cos \alpha \sen \beta) + (\sen \alpha \cos \beta - \cos \alpha \sen \beta)}{2} \\
   &= \dfrac{2 \sen \alpha \cos \beta}{2} \\
   &= \sen \alpha \cos \beta
  \end{align*}
  #+end_demostracion

+ 120
  #+begin_teorema
  $\sen(a) + \sen(b) =
  2\sen\left(\dfrac{a+b}{2}\right)\cos\left(\dfrac{a-b}{2}\right)$
  #+end_teorema
  #+begin_demostracion
  (En ProofWiki [[https://proofwiki.org/wiki/Prosthaphaeresis_Formulas/Sine_plus_Sine][Prosthaphaeresis formulas/Sine plus sine]]).

  \begin{align*}
    &  2 \sen\left(\dfrac{\alpha+\beta}{2}\right)
         \cos\left(\dfrac{\alpha-\beta}{2}\right) \\
    &= 2 \dfrac{\sen\left(\dfrac{\alpha+\beta}{2} + \dfrac{\alpha-\beta}{2}\right) +
                \sen\left(\dfrac{\alpha+\beta}{2} - \dfrac{\alpha-\beta}{2}\right)}
               {2}
         & \mbox{Fórmula de Simpson} \\
    &= \sen \frac{2\alpha}{2} + \sen \frac{2\beta}{2} \\
    &= \sen \alpha + \sen \beta \\
  \end{align*}
  #+end_demostracion

+ 120
  #+begin_teorema
  $\sen(a) - \sen(b) =
  2\cos\left(\dfrac{a+b}{2}\right)\sen\left(\dfrac{a-b}{2}\right)$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Prosthaphaeresis_Formulas/Sine_minus_Sine][Prosthaphaeresis formulas/sine minus sine]])

  \begin{align*}
    &  2 \cos\left(\dfrac{\alpha+\beta}{2}\right)
         \sen\left(\dfrac{\alpha-\beta}{2}\right) \\
    &= 2 \dfrac{\sen\left(\dfrac{\alpha-\beta}{2} + \dfrac{\alpha+\beta}{2}\right) +
                \sen\left(\dfrac{\alpha-\beta}{2} - \dfrac{\alpha+\beta}{2}\right)}
               {2}
         & \mbox{Fórmula de Simpson} \\
    &= \sen \frac{2\alpha}{2} - \sen \frac{2\beta}{2} \\
    &= \sen \alpha - \sen \beta \\
  \end{align*}
  #+end_demostracion

+ Fórmula de Simpson de coseno por coseno: \\
  #+begin_teorema
  $\cos \alpha \cos \beta = \dfrac{\cos(\alpha-\beta) + \cos(\alpha+\beta)}{2}$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Simpson%27s_Formulas/Cosine_by_Cosine][Simpson's Formulas/Cosine by Cosine]])

  \begin{align*}
   &  \dfrac{\cos(\alpha-\beta) + \sen(\alpha+\beta)}{2} \\
   &= \dfrac{(\cos \alpha \cos \beta + \sen \alpha \sen \beta) + (\cos \alpha \cos \beta - \sen \alpha \sen \beta)}{2} \\
   &= \dfrac{2 \cos \alpha \cos \beta}{2} \\
   &= \cos \alpha \cos \beta
  \end{align*}
  #+end_demostracion

+ 120
  #+begin_teorema
  $\cos a  + \cos b  =
  2\cos\left(\dfrac{a+b}{2}\right)\cos\left(\dfrac{a-b}{2}\right)$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Prosthaphaeresis_Formulas/Cosine_plus_Cosine][Prosthaphaeresis Formulas/Cosine plus Cosine]]).

  \begin{align*}
    &  2 \cos\left(\dfrac{\alpha+\beta}{2}\right)
         \cos\left(\dfrac{\alpha-\beta}{2}\right) \\
    &= 2 \dfrac{\cos\left(\dfrac{\alpha-\beta}{2} - \dfrac{\alpha-\beta}{2}\right) +
                \cos\left(\dfrac{\alpha+\beta}{2} + \dfrac{\alpha-\beta}{2}\right)}
               {2}
         & \mbox{Fórmula de Simpson} \\
    &= \cos \frac{2\beta}{2} + \cos \frac{2\alpha}{2} \\
    &= \cos \alpha + \cos \beta \\
  \end{align*}
  #+end_demostracion

  + 120
  #+begin_teorema
  $\cos a  - \cos b  =
  -2\sen\left(\dfrac{a+b}{2}\right)\sen\left(\dfrac{a-b}{2}\right)$
  #+end_teorema
  #+begin_demostracion
  (en ProofWiki [[https://proofwiki.org/wiki/Prosthaphaeresis_Formulas/Cosine_minus_Cosine][Prosthaphaeresis Formulas/Cosine minus Cosine]]).

  \begin{align*}
    &  -2 \sen\left(\dfrac{\alpha+\beta}{2}\right)
          \sen\left(\dfrac{\alpha-\beta}{2}\right) \\
    &= -2 \dfrac{\cos\left(\dfrac{\alpha+\beta}{2} - \dfrac{\alpha-\beta}{2}\right) -
                 \cos\left(\dfrac{\alpha+\beta}{2} + \dfrac{\alpha-\beta}{2}\right)}
               {2}
         & \mbox{Fórmula de Simpson} \\
    &= -\left(\cos \frac{2\beta}{2} - \cos \frac{2\alpha}{2}\right) \\
    &= \cos \alpha - \cos \beta \\
  \end{align*}
  #+end_demostracion
